ALTER TABLE food DROP COLUMN IF  EXISTS coach;
ALTER TABLE breakfast DROP COLUMN IF  EXISTS coach;
ALTER TABLE am_snack DROP COLUMN IF  EXISTS coach;
ALTER TABLE lunch DROP COLUMN IF  EXISTS coach;
ALTER TABLE pm_snack DROP COLUMN IF  EXISTS coach;
ALTER TABLE dinner DROP COLUMN IF  EXISTS coach;
