ALTER TABLE food
ALTER COLUMN coach SET NOT NULL;

ALTER TABLE breakfast
ALTER COLUMN coach SET NOT NULL;

ALTER TABLE am_snack
ALTER COLUMN coach SET NOT NULL;

ALTER TABLE lunch
ALTER COLUMN coach SET NOT NULL;

ALTER TABLE pm_snack
ALTER COLUMN coach SET NOT NULL;

ALTER TABLE dinner
ALTER COLUMN coach SET NOT NULL;


